#!/bin/sh

TERMINE_WIKI_LINK='https://wiki.das-labor.org/index.php?title=Spezial%3ASemantische_Suche&q=%5B%5Bev_title%3A%3A%2B%5D%5D%5B%5Bev_start%3A%3A%2B%5D%5D&po=%3FEv+title%3Dsummary%0D%0A%3FEv+start=start%0D%0A%3FEv+end=end%0D%0A%3FEv+abstract%3DKurztext%0D%0A%3FEv+icon%3Dicon%0D%0A%3FEv+color%3Dcolor%0D%0A%3FEv+place%0D%0A&eq=yes&p%5Bformat%5D=icalendar&sort_num=&order_num=ASC&p%5Blimit%5D=5000&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%E2%80%A6+weitere+Ergebnisse&p%5Bdefault%5D=&p%5Btitle%5D=&p%5Bdescription%5D=&eq=yes'

cd /srv/www.das-labor.org/bin

curl "$TERMINE_WIKI_LINK" --compressed --silent > /srv/www.das-labor.org/htdoc/termine.ics

./parse-ical > /dev/null

# update rss & html
cd /srv/www.das-labor.org/bin/parse-labor-wiki-termine
./update-web /srv/www.das-labor.org/htdoc/ > /dev/null
./update-rss_talks /srv/www.das-labor.org/htdoc/  > /dev/null
cd /srv/www.das-labor.org/bin/
./update-ics-rss-htmlsnippet.rb > /dev/null

