#!/bin/sh

php /srv/www.das-labor.org/w/maintenance/generateSitemap.php --server=www.das-labor.org --fspath=/srv/www.das-labor.org/htdoc/w-sitemaps/ --compress=no

# Ping Google
wget -q -O - http://www.google.com/webmasters/tools/ping?sitemap=http://www.das-labor.org/sitemap.xml

# Ping Moreover (MSN)
wget -q -O - http://api.moreover.com/ping?u=http://www.das-labor.org/sitemap.xml

# Ping Yahoo
wget -q -O - http://search.yahooapis.com/SiteExplorerService/V1/ping?sitemap=http://www.das-labor.org/sitemap.xml
