#!/usr/bin/env ruby

require 'rexml/document'
require 'date'

LOOKAHEAD=3    # Tage in die Zukunft gucken.
LOOKPAST=10    # alte Termine weiter anzeigen (Tage)
XMLSOURCE=ARGV[0]+"/announce.xml";

class Termin
  attr_reader :day, :wday, :month, :year, :text, :link, :date, :datestr, :hour, :min;

  def initialize(xml)
    @day   = xml.elements["day"].text.to_i;
    @wday  = xml.elements["wday"].text;
    @month = xml.elements["month"].text.to_i;
    @year  = xml.elements["year"].text.to_i;
    @text  = xml.elements["text"].text;
    @link  = xml.elements["link"].text;
    @hour  = xml.elements["hour"].text.to_i;
    @min   = xml.elements["min"].text;
    
    @year += 2000 if @year < 2000;

    @date  = Date.new( @year, @month, @day );
    @month = @date.strftime("%m") 
    @day = @date.strftime("%d") 
    @datestr = "#{@day}.#{@month}.#{@year} (#{@wday})"
  end

  def to_s
    return @datestr + " - " + @text;
  end
end


timestamp = Time.now.to_i

doc = REXML::Document.new( File.new( XMLSOURCE ));
at = Array.new

doc.elements.each("/termine/termin") { |tx|
    at.push(Termin.new(tx));
}


##############################################################################
# Sichtbare Termine ##########################################################
at.sort!{ |a,b| a.date <=> b.date }  # sortiere liste

termine = Array.new;
at.each { |t|
  if (((Date.today+LOOKAHEAD) > t.date) == (t.date > (Date.today-LOOKPAST))) then
    termine.push(t);
  end
}

puts "Choosing Termine...";
termine.each { |t|
  puts "    #{t.date}  #{t.hour}:#{t.min}  #{t.text}";
}

##############################################################################
# RSS Output #################################################################
puts "Generating RSS 2.0..."
rss20out = File.new( ARGV[0]+"/announce.rss", "w" );
rss20out.puts "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?> \n 
<rss version=\"2.0\"> \n 
<channel> \n 
<title>LABOR Bochum: Veranstaltungen in 3 Tagen</title> \n
<link>http://www.das-labor.org</link> \n 
<description>Terminfeed des LABORs bis 3 Tage in die Zukunft (genutzt vom Kalenderbot)</description> \n 
<language>de-de</language> \n
<pubDate>#{Time.now.strftime("%a, %d %b %Y %H:%M:%S %Z")}</pubDate>";
termine.each { |term|
    rss20out.puts "<item>\n<title>#{term.text}: Am #{term.day}.#{term.month}.#{term.year} (#{term.wday}) um #{term.hour}:#{term.min}</title>\n<description>#{term.day}.#{term.month}.#{term.year} (#{term.wday}) #{term.hour}:#{term.min} - #{term.text}</description>\n<link>#{term.link}</link>\n</item>\n\n";
}
rss20out.puts "</channel> \n</rss>";
rss20out.close;
